name: Testing Phase 1
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the code from github
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test Code
        run: npm run test
      - name: Build Code
        run: npm run build
      - name: Deploying the code
        run: echo "Deploying....."
